package main

import (
	"dropbear/broker/alpaca"
	"dropbear/decimal"
	"dropbear/symbol"
	"fmt"
	"os"
	"os/exec"
	"slices"
)

func main() {
	client := alpaca.NewClient()

	// get latest assets data
	err := client.SyncAssets()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to sync assets: %v\n", err)
		os.Exit(1)
	}

	// sort symbols for deterministic output
	symbols := make([]symbol.Symbol, 0, len(alpaca.Assets))
	for sym := range alpaca.Assets {
		symbols = append(symbols, sym)
	}
	slices.Sort(symbols)

	// now open assetsdata.go for writing
	path := "broker/alpaca/assetsdata.go"
	out, err := os.Create(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", path, err)
		os.Exit(1)
	}

	fmt.Fprintln(out, "// Code generated by go run ./broker/alpaca/cmd/genassets. DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "package alpaca")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "import (")
	fmt.Fprintln(out, "\t\"dropbear/ds\"")
	fmt.Fprintln(out, "\t\"dropbear/symbol\"")
	fmt.Fprintln(out, ")")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "var Assets = map[symbol.Symbol]*Asset{")

	for _, sym := range symbols {
		a := alpaca.Assets[sym]
		fmt.Fprintf(out, "\t0x%x: { // %s\n", sym, sym)
		fmt.Fprintf(out, "\t\tSymbol: 0x%x,\n", a.Symbol)
		fmt.Fprintf(out, "\t\tExchange: %#v,\n", a.Exchange)
		fmt.Fprintf(out, "\t\tClass: %#v,\n", a.Class)
		fmt.Fprintf(out, "\t\tStatus: %#v,\n", a.Status)
		fmt.Fprintf(out, "\t\tName: %q,\n", a.Name)
		fmt.Fprintf(out, "\t\tID: %q,\n", a.ID)
		printDecimal(out, "MarginRequirementLong", a.MarginRequirementLong.Load())
		printDecimal(out, "MarginRequirementShort", a.MarginRequirementShort.Load())
		printDecimal(out, "MinTradeIncrement", a.MinTradeIncrement.Load())
		printDecimal(out, "PriceIncrement", a.PriceIncrement.Load())
		printBool(out, "IPO", a.IPO.Load())
		printBool(out, "Tradable", a.Tradable.Load())
		printBool(out, "Marginable", a.Marginable.Load())
		printBool(out, "Shortable", a.Shortable.Load())
		printBool(out, "EasyToBorrow", a.EasyToBorrow.Load())
		printBool(out, "Fractionable", a.Fractionable.Load())
		printBool(out, "FractionableExtHours", a.FractionableExtHours.Load())
		printBool(out, "HasOptions", a.HasOptions.Load())
		printBool(out, "OptionsLateClose", a.OptionsLateClose.Load())
		printBool(out, "PTPNoException", a.PTPNoException.Load())
		printBool(out, "PTPWithException", a.PTPWithException.Load())
		fmt.Fprintf(out, "\t},\n")
	}

	fmt.Fprintf(out, "}\n")
	out.Close()

	// spawn go fmt on path
	fmtCmd := exec.Command("go", "fmt", path)
	fmtCmd.Stderr = os.Stderr
	fmtCmd.Stdout = os.Stdout
	err = fmtCmd.Run()
	if err != nil {
		fmt.Fprintf(os.Stderr, "go fmt failed: %v\n", err)
		os.Exit(1)
	}
}

func printDecimal(out *os.File, s string, d decimal.Decimal) {
	fmt.Fprintf(out, "\t\t%s: %d, // %s\n", s, d, d)
}

func printBool(out *os.File, s string, b bool) {
	if b {
		fmt.Fprintf(out, "\t\t%s: ds.True,\n", s)
	}
}
