// Generates assetsdata.go from Alpaca API.
//
// Usage: go run ./broker/alpaca/cmd/genassets > broker/alpaca/assetsdata.go
package main

import (
	"dropbear/broker/alpaca"
	"fmt"
	"log"
	"sort"
)

func main() {
	client := alpaca.NewClient()
	assets, err := client.GetAssets()
	if err != nil {
		log.Fatalf("failed to fetch assets: %v", err)
	}

	// Sort symbols for deterministic output
	symbols := make([]string, 0, len(assets))
	for sym := range assets {
		symbols = append(symbols, sym)
	}
	sort.Strings(symbols)

	fmt.Println("// Code generated by go run ./broker/alpaca/cmd/genassets. DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package alpaca")
	fmt.Println()
	fmt.Println("var generatedAssets = map[string]*Asset{")

	for _, sym := range symbols {
		a := assets[sym]
		fmt.Printf("\t%q: {\n", sym)
		fmt.Printf("\t\tSymbol: %q,\n", a.Symbol)
		fmt.Printf("\t\tExchange: %d,\n", a.Exchange)
		fmt.Printf("\t\tName: %q,\n", a.Name)
		fmt.Printf("\t\tID: %q,\n", a.ID)
		fmt.Printf("\t\tClass: %d,\n", a.Class)
		fmt.Printf("\t\tStatus: %d,\n", a.Status)
		if a.IPO {
			fmt.Printf("\t\tIPO: true,\n")
		}
		if a.Tradable {
			fmt.Printf("\t\tTradable: true,\n")
		}
		if a.Marginable {
			fmt.Printf("\t\tMarginable: true,\n")
		}
		if a.Shortable {
			fmt.Printf("\t\tShortable: true,\n")
		}
		if a.EasyToBorrow {
			fmt.Printf("\t\tEasyToBorrow: true,\n")
		}
		if a.Fractionable {
			fmt.Printf("\t\tFractionable: true,\n")
		}
		if a.FractionableExtHours {
			fmt.Printf("\t\tFractionableExtHours: true,\n")
		}
		if a.HasOptions {
			fmt.Printf("\t\tHasOptions: true,\n")
		}
		if a.OptionsLateClose {
			fmt.Printf("\t\tOptionsLateClose: true,\n")
		}
		if a.PTPNoException {
			fmt.Printf("\t\tPTPNoException: true,\n")
		}
		if a.PTPWithException {
			fmt.Printf("\t\tPTPWithException: true,\n")
		}
		fmt.Printf("\t\tMarginRequirementLong: %d,\n", a.MarginRequirementLong)
		fmt.Printf("\t\tMarginRequirementShort: %d,\n", a.MarginRequirementShort)
		fmt.Printf("\t\tMinTradeIncrement: %d,\n", a.MinTradeIncrement)
		fmt.Printf("\t\tPriceIncrement: %d,\n", a.PriceIncrement)
		fmt.Printf("\t},\n")
	}

	fmt.Println("}")
}
