// sipjsonl2go converts SIP JSONL files to Go source code.
//
// Usage:
//
//	go run ./broker/alpaca/cmd/sipjsonl2go ~/sipdata-compact.jsonl > sip_data.go
//
// This generates Go code with typed struct literals that can be
// compiled into your program, avoiding JSON parsing at runtime.
package main

import (
	"bufio"
	"dropbear/broker/alpaca"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: %s <file.jsonl> [file2.jsonl ...]\n", os.Args[0])
		os.Exit(1)
	}

	fmt.Println("// Code generated by sipjsonl2go. DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package main")
	fmt.Println()
	fmt.Println("import (")
	fmt.Println("\t\"dropbear/broker/alpaca\"")
	fmt.Println("\t\"dropbear/clocky\"")
	fmt.Println("\t\"dropbear/decimal\"")
	fmt.Println(")")
	fmt.Println()
	fmt.Println("var (")
	fmt.Println("\t_ = alpaca.SIPMessageTypeTrade")
	fmt.Println("\t_ = clocky.Time(0)")
	fmt.Println("\t_ = decimal.Zero")
	fmt.Println(")")
	fmt.Println()

	var trades []alpaca.SIPTrade
	var quotes []alpaca.SIPQuote
	var bars []alpaca.SIPBar
	var statuses []alpaca.SIPStatus

	for _, path := range os.Args[1:] {
		f, err := os.Open(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error opening %s: %v\n", path, err)
			os.Exit(1)
		}

		scanner := bufio.NewScanner(f)
		buf := make([]byte, 0, 64*1024)
		scanner.Buffer(buf, 1024*1024)

		lineNum := 0
		for scanner.Scan() {
			lineNum++
			line := scanner.Bytes()
			if len(line) == 0 {
				continue
			}

			msgType := alpaca.GetSIPMessageType(line)
			switch msgType {
			case 't':
				t, err := alpaca.ParseSIPTradeFast(line)
				if err != nil {
					fmt.Fprintf(os.Stderr, "%s:%d: trade parse error: %v\n", path, lineNum, err)
					continue
				}
				trades = append(trades, t)
			case 'q':
				q, err := alpaca.ParseSIPQuoteFast(line)
				if err != nil {
					fmt.Fprintf(os.Stderr, "%s:%d: quote parse error: %v\n", path, lineNum, err)
					continue
				}
				quotes = append(quotes, q)
			case 'b', 'd', 'u':
				b, err := alpaca.ParseSIPBarFast(line)
				if err != nil {
					fmt.Fprintf(os.Stderr, "%s:%d: bar parse error: %v\n", path, lineNum, err)
					continue
				}
				bars = append(bars, b)
			case 's':
				s, err := alpaca.ParseSIPStatusFast(line)
				if err != nil {
					fmt.Fprintf(os.Stderr, "%s:%d: status parse error: %v\n", path, lineNum, err)
					continue
				}
				statuses = append(statuses, s)
			}
		}

		if err := scanner.Err(); err != nil {
			fmt.Fprintf(os.Stderr, "%s: scanner error: %v\n", path, err)
		}

		f.Close()

		fmt.Fprintf(os.Stderr, "%s: %d trades, %d quotes, %d bars, %d statuses\n",
			filepath.Base(path), len(trades), len(quotes), len(bars), len(statuses))
	}

	if len(trades) > 0 {
		fmt.Printf("var Trades = []alpaca.SIPTrade{\n")
		for _, t := range trades {
			fmt.Printf("\t%#v,\n", t)
		}
		fmt.Println("}")
		fmt.Println()
	}

	if len(quotes) > 0 {
		fmt.Printf("var Quotes = []alpaca.SIPQuote{\n")
		for _, q := range quotes {
			fmt.Printf("\t%#v,\n", q)
		}
		fmt.Println("}")
		fmt.Println()
	}

	if len(bars) > 0 {
		fmt.Printf("var Bars = []alpaca.SIPBar{\n")
		for _, b := range bars {
			fmt.Printf("\t%#v,\n", b)
		}
		fmt.Println("}")
		fmt.Println()
	}

	if len(statuses) > 0 {
		fmt.Printf("var Statuses = []alpaca.SIPStatus{\n")
		for _, s := range statuses {
			fmt.Printf("\t%#v,\n", s)
		}
		fmt.Println("}")
		fmt.Println()
	}
}
