package symbol

const (
	AAPL  = Symbol('A' | 'A'<<8 | 'P'<<16 | 'L'<<24)
	ADBE  = Symbol('A' | 'D'<<8 | 'B'<<16 | 'E'<<24)
	AKAM  = Symbol('A' | 'K'<<8 | 'A'<<16 | 'M'<<24)
	AMD   = Symbol('A' | 'M'<<8 | 'D'<<16)
	AMZN  = Symbol('A' | 'M'<<8 | 'Z'<<16 | 'N'<<24)
	AVGO  = Symbol('A' | 'V'<<8 | 'G'<<16 | 'O'<<24)
	BTI   = Symbol('B' | 'T'<<8 | 'I'<<16)
	GLD   = Symbol('G' | 'L'<<8 | 'D'<<16)
	GOOG  = Symbol('G' | 'O'<<8 | 'O'<<16 | 'G'<<24)
	GOOGL = Symbol('G' | 'O'<<8 | 'O'<<16 | 'G'<<24 | 'L'<<32)
	IBIT  = Symbol('I' | 'B'<<8 | 'I'<<16 | 'T'<<24)
	INTU  = Symbol('I' | 'N'<<8 | 'T'<<16 | 'U'<<24)
	IWM   = Symbol('I' | 'W'<<8 | 'M'<<16)
	META  = Symbol('M' | 'E'<<8 | 'T'<<16 | 'A'<<24)
	MSFT  = Symbol('M' | 'S'<<8 | 'F'<<16 | 'T'<<24)
	NDX   = Symbol('N' | 'D'<<8 | 'X'<<16)
	NVDA  = Symbol('N' | 'V'<<8 | 'D'<<16 | 'A'<<24)
	PM    = Symbol('P' | 'M'<<8)
	QQQ   = Symbol('Q' | 'Q'<<8 | 'Q'<<16)
	RUTW  = Symbol('R' | 'U'<<8 | 'T'<<16 | 'W'<<24)
	SLV   = Symbol('S' | 'L'<<8 | 'V'<<16)
	SPEQX = Symbol('S' | 'P'<<8 | 'E'<<16 | 'Q'<<24 | 'X'<<32)
	SPXW  = Symbol('S' | 'P'<<8 | 'X'<<16 | 'W'<<24)
	SPY   = Symbol('S' | 'P'<<8 | 'Y'<<16)
	TLT   = Symbol('T' | 'L'<<8 | 'T'<<16)
	TSLA  = Symbol('T' | 'S'<<8 | 'L'<<16 | 'A'<<24)
	VIX   = Symbol('V' | 'I'<<8 | 'X'<<16)
	VIXW  = Symbol('V' | 'I'<<8 | 'X'<<16 | 'W'<<24)
	XSP   = Symbol('X' | 'S'<<8 | 'P'<<16)
)
