// gen.kraken fetches Kraken asset pairs and generates Go code for symbol mapping.
//
// Usage:
//
//	go run ./cmd/gen.kraken > exchange/kraken/symbols.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"sort"
)

func main() {
	// Fetch assets
	assets := fetchAssets()

	// Fetch asset pairs
	pairs := fetchAssetPairs()

	// Build symbol -> normalized name mapping
	symbolMap := make(map[string]string)

	// From assets: map altname to normalized form
	for symbol, asset := range assets {
		altname := asset.Altname
		if altname != "" && altname != symbol {
			symbolMap[symbol] = altname
		}
	}

	// From pairs: extract base/quote mappings
	for pairSymbol, pair := range pairs {
		// Map the pair's base to its display symbol
		if pair.Base != "" && pair.BaseDisplaySymbol != "" && pair.Base != pair.BaseDisplaySymbol {
			symbolMap[pair.Base] = pair.BaseDisplaySymbol
		}
		// Map the pair's quote to its display symbol
		if pair.Quote != "" && pair.QuoteDisplaySymbol != "" && pair.Quote != pair.QuoteDisplaySymbol {
			symbolMap[pair.Quote] = pair.QuoteDisplaySymbol
		}
		// Map wsname components if available
		if pair.WSName != "" && pair.Altname != "" {
			// wsname is like "XBT/USD", altname is like "XBTUSD"
			symbolMap[pairSymbol] = pair.WSName
			symbolMap[pair.Altname] = pair.WSName
		}
	}

	// Sort keys for deterministic output
	var keys []string
	for k := range symbolMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Generate Go code
	fmt.Println("// Code generated by go run ./cmd/gen.kraken. DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package kraken")
	fmt.Println()
	fmt.Println("// SymbolToNormalized maps Kraken's internal symbols to normalized names.")
	fmt.Println("// Examples: XXBT -> XBT, XETH -> ETH, ZUSD -> USD")
	fmt.Println("var SymbolToNormalized = map[string]string{")
	for _, k := range keys {
		v := symbolMap[k]
		if k != v { // only include if different
			fmt.Printf("\t%q: %q,\n", k, v)
		}
	}
	fmt.Println("}")
	fmt.Println()

	// Generate pair info
	fmt.Println("// PairInfo contains base/quote info for a trading pair.")
	fmt.Println("type PairInfo struct {")
	fmt.Println("\tBase  string // e.g. \"BTC\"")
	fmt.Println("\tQuote string // e.g. \"USD\"")
	fmt.Println("}")
	fmt.Println()

	// Sort pair keys
	var pairKeys []string
	for k := range pairs {
		pairKeys = append(pairKeys, k)
	}
	sort.Strings(pairKeys)

	fmt.Println("// Pairs maps Kraken pair symbols to their base/quote currencies.")
	fmt.Println("var Pairs = map[string]PairInfo{")
	for _, k := range pairKeys {
		p := pairs[k]
		base := normalizeSymbol(p.Base, symbolMap)
		quote := normalizeSymbol(p.Quote, symbolMap)
		// Also include altname and wsname as keys pointing to same info
		fmt.Printf("\t%q: {%q, %q},\n", k, base, quote)
		if p.Altname != "" && p.Altname != k {
			fmt.Printf("\t%q: {%q, %q},\n", p.Altname, base, quote)
		}
		if p.WSName != "" {
			fmt.Printf("\t%q: {%q, %q},\n", p.WSName, base, quote)
		}
	}
	fmt.Println("}")
	fmt.Println()

	// Generate helper function
	fmt.Println("// SplitPair splits a Kraken pair symbol into base and quote currencies.")
	fmt.Println("// Returns normalized currency names (e.g. \"BTC\", \"USD\" not \"XXBT\", \"ZUSD\").")
	fmt.Println("func SplitPair(pair string) (base, quote string, ok bool) {")
	fmt.Println("\tif info, found := Pairs[pair]; found {")
	fmt.Println("\t\treturn info.Base, info.Quote, true")
	fmt.Println("\t}")
	fmt.Println("\treturn \"\", \"\", false")
	fmt.Println("}")
}

func normalizeSymbol(s string, symbolMap map[string]string) string {
	if n, ok := symbolMap[s]; ok {
		s = n
	}
	// Normalize XBT to BTC for consistency with other exchanges
	if s == "XBT" {
		return "BTC"
	}
	// Normalize XDG to DOGE
	if s == "XDG" {
		return "DOGE"
	}
	return s
}

type Asset struct {
	Altname string `json:"altname"`
}

type AssetPair struct {
	Altname            string `json:"altname"`
	WSName             string `json:"wsname"`
	Base               string `json:"base"`
	Quote              string `json:"quote"`
	BaseDisplaySymbol  string `json:"base_display_symbol"`
	QuoteDisplaySymbol string `json:"quote_display_symbol"`
}

type AssetsResponse struct {
	Error  []string         `json:"error"`
	Result map[string]Asset `json:"result"`
}

type AssetPairsResponse struct {
	Error  []string             `json:"error"`
	Result map[string]AssetPair `json:"result"`
}

func fetchAssets() map[string]Asset {
	resp, err := http.Get("https://api.kraken.com/0/public/Assets")
	if err != nil {
		log.Fatalf("fetching assets: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	var result AssetsResponse
	if err := json.Unmarshal(body, &result); err != nil {
		log.Fatalf("parsing assets: %v", err)
	}
	if len(result.Error) > 0 {
		log.Fatalf("kraken error: %v", result.Error)
	}
	return result.Result
}

func fetchAssetPairs() map[string]AssetPair {
	resp, err := http.Get("https://api.kraken.com/0/public/AssetPairs")
	if err != nil {
		log.Fatalf("fetching asset pairs: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	var result AssetPairsResponse
	if err := json.Unmarshal(body, &result); err != nil {
		log.Fatalf("parsing asset pairs: %v", err)
	}
	if len(result.Error) > 0 {
		log.Fatalf("kraken error: %v", result.Error)
	}
	return result.Result
}
